#!/bin/sh
DEVICES=
cd /sys/class/input
for evdev in event*; do
	PHYS="`cat "$evdev/device/phys"`"
	if [ "$PHYS" = ALSA ]; then
		DEVICES="$DEVICES /dev/input/$evdev"
	fi
done
exec /usr/lib/jacklistener/jacklistenerd $DEVICES
